<?php



/**
 * Implements hook_field_formatter_info().
 */
function friendrelationformatter_field_formatter_info() {
    return array(
        'friendrelationformatter_formatter' => array(//Machine name of the formatter
            'label' => t('Friend relation formatter'),
            'field types' => array('relation')
        ),
    );
}

/**
 * Can be used to render a field of friends.
 */
function friendrelationformatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
    global $user;

    $element = array();
    list($entity_id) = entity_extract_ids($entity_type, $entity);
    foreach ($items as $delta => $item) {
        //Only print the relations where I am the source
        $relation = (object) $item;
        $sourceUserId = $relation->endpoints[LANGUAGE_NONE][0]['entity_id'];
        $targetUserId = $relation->endpoints[LANGUAGE_NONE][1]['entity_id'];

        $friendArray = array();

        if ($sourceUserId == $user->uid) {
            $frienduser = user_load($targetUserId);
            $friendLink = "<a href='?q=user/".$frienduser->uid."'>".$frienduser->name. "</a>";
            array_push($friendArray, $friendLink);
        }
        
        $element[$delta]["myfriends"] = array(
         '#theme' => 'item_list',
        '#items' => $friendArray,
        '#type' => 'ul',
            
        );
    }
    return $element;
}
?>
